apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: declarative-guestbook
  # You'll usually want to add your resources to the argocd namespace.
  namespace: ifs-argocd
spec:
  project: default
  
  # Sources field specifies the list of sources for the application
  source:
    path: guestbook
    repoURL: https://github.com/mak-xoriant/argocd-example-apps.git
    targetRevision: master
  
  # Destination cluster and namespace to deploy the application
  destination:
    namespace: declarative-guestbook
    # cluster API URL
    server: https://kubernetes.default.svc
    
  # Sync policy
  syncPolicy:
    syncOptions:
      - CreateNamespace=true